import Head from "next/head";
import Navbar from "./components/navbar";
import Hero from "./components/hero";
import Skill from "./components/skill";
import Works from "./components/works";
import Profile from "./components/profile";
import Contact from "./components/contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>kakuzoサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <div className="mt-12 tab:mt-32">
        <Skill />
      </div>
      <div className="mt-24 tab:mt-48">
        <Works />
      </div>
      <div className="mt-24 tab:mt-48">
        <Profile />
      </div>
      <div className="mt-24 tab:mt-48">
        <Contact />
      </div>
    </div>
  );
}
