import { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "./components/navbar";
import Hero from "./components/hero";
import Skill from "./components/skill";
import Works from "./components/works";
import Profile from "./components/profile";
import Contact from "./components/contact";

export default function Home() {
  const [darkTheme, setDarkTheme] = useState("");

  const handleToggle = (e) => {
    setDarkTheme(e.target.checked);
  };

  useEffect(() => {
    if (darkTheme !== undefined) {
      if (darkTheme) {
        document.documentElement.setAttribute("data-theme", "dark");
        window.localStorage.setItem("theme", "dark");
      } else {
        document.documentElement.removeAttribute("data-theme");
        window.localStorage.setItem("theme", "light");
      }
    }
  }, [darkTheme]);

  return (
    <div>
      <Head>
        <title>kakuzoサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <div className="mt-32">
        <Skill />
      </div>
      <div className="mt-48">
        <Works />
      </div>
      <div className="mt-48">
        <Profile />
      </div>
      <div className="mt-48">
        <Contact />
      </div>
    </div>
  );
}
